#!/usr/bin/env python

Import('env')

env.add_source_files(env.drivers_sources,"*.cpp")
env.add_source_files(env.drivers_sources,"*.mm")
env.add_source_files(env.drivers_sources,"*.m")

SConscript("shaders/SCsub")